name: Makefile CI

# ubuntu apt doesn't have esbuild until 21.04
# (as of 2021-10-17, ubuntu-latest is 20.04)

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Install dependencies
      run: brew update && brew install esbuild yarn
      
    - name: Yarn
      run: yarn install
      
    - name: Clean
      run: make clean

    - name: Make
      run: make
