name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install esbuild
      
    - name: Clean
      run: make clean

    - name: Make
      run: make
